### ISSUE TITLE
Messy 404 Page

### ISSUE THREAD

**Issue by HighnessAtharva** [yatharthb97/yatharthb97.github.io#1]
Hey, I was going through your blog site and came across this. Upon visiting a unavailable page, there would ideally be a 404 error but there is some issue with templating for your site. 
![checkthis](https://user-images.githubusercontent.com/68660002/178143360-33a5b290-2fb2-4bca-bd72-84a36d25baad.JPG)

PS - Your Hugo PaperMod site is amazing. I was inspired by it and made my own. You can check it out [here.](https://atharvashah.netlify.app/)

**Comment by yatharthb97** [comment]
Hey, @HighnessAtharva thanks for pointing it out. I think the page failed to render the GoAT code block. I will fix it. 

P.S.: Congratulations on your excellent website too! :)

**Comment by yatharthb97** [comment]
Fixed: https://yatharthb97.github.io/no_such_page
